name: well-auction
main: net.gasull.well.auction.WellAuction
version: 0.0.1
depend: [Vault]
commands:
  wellauction:
    description: This allow you to manage Auction Houses.
    usage: /<command> create [player]
    permission: well.auction
    permission-message: You don't have <permission>